name: Continuous Deployment Workflow

on:
  workflow_call :
    inputs:
      github_sha:
        type: string
        description: "The SHA of the commit that triggered the workflow"
        required: true
      app_folder:
        type: string
        default: "sample_app"
        description: "The folder where the app is located"
        required: false
      test_folder:
        type: string
        default: "tests"
        description: "The folder where the tests are located"
    secrets:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub access token"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define Docker image tag
        id: docker_meta
        run: |
          # The image was tagged with the short SHA of the triggering commit
          SHA=${{ inputs.github_sha }}
          echo "tag=pinoched/liquia_cicd:${SHA}" >> $GITHUB_OUTPUT

      - name: Pull Docker Image from Registry
        run: docker pull ${{ steps.docker_meta.outputs.tag }}

      - name: 🎭 Mock Deployment by Running the Image
        id: mock_deployment
        run: |
          # Run the image and capture the output
          docker run ${{ steps.docker_meta.outputs.tag }}

      - name: Post Deployment Success Comment
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run_link = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `
              ### ✅ Deployment Succeeded

              The mock deployment was successful.
              - **Image:** \`${{ steps.docker_meta.outputs.tag }}\`
              - **Details:** [View Workflow Run](${run_link})
              `
            });

      - name: Post Deployment Failure Comment
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run_link = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `
              ### ❌ Deployment Failed

              The mock deployment failed. Please check the logs for details.
              - **Image:** \`${{ steps.docker_meta.outputs.tag }}\`
              - **Details:** [View Workflow Run](${run_link})
              `
            });